version: '3.8'

services:
  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #
  #                          Postgres                                  #
  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #
  postgres:
    image: postgres:15-alpine
    container_name: url-shortener-db-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: url_shortener
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    networks:
      - url-shortener-network-dev

volumes:
  db_data_dev:
    driver: local

networks:
  url-shortener-network-dev:
    driver: bridge
