name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install npm-check-updates
        run: npm install -g npm-check-updates

      - name: Check for updates
        id: check-updates
        run: |
          ncu --jsonUpgraded > updates.json
          if [ -s updates.json ]; then
            echo "has_updates=true" >> $GITHUB_OUTPUT
            echo "Updates available:"
            cat updates.json
          else
            echo "has_updates=false" >> $GITHUB_OUTPUT
            echo "No updates available"
          fi

      - name: Update dependencies
        if: steps.check-updates.outputs.has_updates == 'true'
        run: |
          ncu -u
          npm install

      - name: Run tests after update
        if: steps.check-updates.outputs.has_updates == 'true'
        run: |
          npm run prisma:generate
          npm run ci:lint
          npm run ci:test
        env:
          NODE_ENV: test
          JWT_SECRET: test-jwt-secret

      - name: Create Pull Request
        if: steps.check-updates.outputs.has_updates == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "🔄 Automated Dependency Updates"
          body: |
            ## 📦 Dependency Updates
            
            This PR contains automated dependency updates generated by GitHub Actions.
            
            ### Changes
            ```json
            $(cat updates.json)
            ```
            
            ### Verification
            - ✅ Linting passed
            - ✅ Tests passed
            - ✅ Build successful
            
            Please review the changes and merge if appropriate.
            
            ---
            *This PR was created automatically by the dependency update workflow*
          branch: dependency-updates
          delete-branch: true
